language: julia
addons:
  apt_packages:
    - gfortran
os:
  - linux
julia:
  - 1.2
  - 1.3
  - 1.4
  - 1.5

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: test
      script:
        - julia -e 'import Pkg; Pkg.test("ForneyLab")'
      after_success: skip
    - stage: documentation
      julia: 1.5
      addons:
        apt-packages:
          - graphviz
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

stages:
  - test
  - documentation